import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import { Banner } from "../components/Banner";
import { Header } from "../components/Header";

const Home: NextPage = () => {
  return (
    // <div>
    //   <Head>
    //     <title>worldtrip</title>
    //     {/* <meta name="description" content="Generated by create next app" /> */}
    //     {/* <link rel="icon" href="/favicon.ico" /> */}
    //   </Head>

    // </div>
    <Flex direction="column">
      <Header />
      <Banner />
    </Flex>
  );
};

export default Home;
